### ISSUE TITLE
Add MessageHUD

### ISSUE THREAD

**Issue by Morbix** [OpenCraft/OCHuds#1]

**Comment by Morbix** [comment]
@giovanepossebon done?

**Comment by giovanepossebon** [comment]
Done #14

**Comment by Morbix** [comment]
@giovanepossebon fix this pods issue:

![captura de tela 2016-08-17 as 17 50 59](https://cloud.githubusercontent.com/assets/590584/17752674/4f28679a-64a3-11e6-8b3c-d5ec0178b7dd.png)

**Execute this before submit the PR:**

```
$ pod lib lint
```

**Comment by giovanepossebon** [comment]
Solved!

**Comment by Morbix** [comment]
Released with 1.2.0
